### ISSUE TITLE
Investigate dropping or deprecating Neon.Tasks classes

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonSDK#51]
We're using [AsyncKeyedLock](https://github.com/MarkCiliaVincenti/AsyncKeyedLock) in the k8s operator SDK. Investigate using it instead of [AsyncMutex](https://api-docs.neonforge.com/neonsdk/api/Neon.Tasks.AsyncMutex.html)

**Comment by jefflill** [comment]
**WONT-FIX:** This is not a lot of code and we use it in a lot of places, so I'm going to leave it alone.
