### ISSUE TITLE
LogErrorEx() doesn't work when an exception is passed

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonSDK#59]
This works:
```
logger?.LogErrorEx("There was a bug in the code.");
```

This doesn't
```
var error = new Exception();
logger?.LogErrorEx(error, "There was a bug in the code.");
```

**Comment by jefflill** [comment]
So what was the problem with this?  I reviewed the code and it looks OK but haven't tried executing this yet.

**Comment by jefflill** [comment]
So the method isn't logging anything here.  This looks like a problem with MSFT's logger implementation.

**Comment by jefflill** [comment]
Closing as **BY-DESIGN**.  Logging an unthrown exception doesn't really make sense and ignoring this is the standard MSFT logger behavior, so we're not going to try to fight it.
