### ISSUE TITLE
Nuget of 3.0.0

### ISSUE THREAD

**Issue by edikk202** [nforgeio/neonSDK#62]
We are moving to dotnet 7 and we are waiting for cadence 3.0.0
I sow that 3.0.0 is released but the nuget is not published yet. Please publich the nuget of 3.0.0

**Comment by jefflill** [comment]
Unfortunately, we've decided to drop support for Uber Cadence starting with neonSDK v3.0.0.  We did spend some time working on a port to Temporal.io, which is the successor to Cadence, but abandoned that after Temporal committed to developing an official .NET client:

https://temporal.io 
https://github.com/temporalio/sdk-dotnet

We haven't tried the new client out yet, but it looks like it's progressing nicely.
